import { formatBytes, formatDuration } from '../../../shared/lib/format.ts';
import type { DatasetLoadReport } from '../../../shared/lib/fetch-dataset.ts';
import { DataTable } from '../../../shared/ui/DataTable.tsx';
import { Section } from '../../../shared/ui/Section.tsx';

interface DatasetsSectionProps {
  readonly id: string;
  readonly reports: readonly DatasetLoadReport[];
}

export function DatasetsSection({ id, reports }: DatasetsSectionProps) {
  return (
    <Section
      id={id}
      title="Dataset files"
      description="Generated by `npm run data` from pinned raw sources. Sizes are uncompressed; static hosts serve them gzip-compressed."
    >
      <DataTable
        rows={reports}
        rowKey={(report) => report.path}
        columns={[
          { header: 'File', render: (report) => <code>{report.path}</code> },
          { header: 'Size', align: 'end', render: (report) => formatBytes(report.bytes) },
          {
            header: 'Download',
            align: 'end',
            render: (report) => formatDuration(report.downloadMs),
          },
          { header: 'Parse', align: 'end', render: (report) => formatDuration(report.parseMs) },
          {
            header: 'Validate & index',
            align: 'end',
            render: (report) => formatDuration(report.processMs),
          },
        ]}
      />
    </Section>
  );
}
